name: Build latest
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
    inputs:
      build_all:
        description: Build every single Minecraft version
        default: 'false'
        required: false
        type: boolean
  repository_dispatch: { }
jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build go binary
        run: |
          go build
      - name: Run binary
        env:
          GITHUB_REGISTRY: ghcr.io/${{ github.repository }}
        run: |
          if [ -z ${{github.event.inputs.build_all}}]
          then
          export all_flag=false
          else
          export all_flag=true
          fi
          ./minecraft-server --all=$all_flag

